deepstream:
  nodes:
  - type: nvurisrcbin
    name: nvurisrcbin
    properties:
      uri: file:///root/attachments/images/video1.png
      disable-audio: true
      select-rtp-protocol: 4
      num-buffers: 1
  - type: nvstreammux
    name: nvstreammux
    properties:
      batch-size: 1
      width: 1920
      height: 1080
      enable-padding: false
      batched-push-timeout: 40000
      gpu-id: 0
      live-source: false
  - type: nvinfer
    name: pgie
    properties:
      config-file-path: /root/configs/generator/yolo26n_det_image/pgie.yml
      batch-size: 1
      gpu-id: 0
  - type: nvdsanalytics
    name: nvdsanalytics
    properties:
      config-file: /root/configs/generator/yolo26n_det_image/nvdsanalytics.yml
      gpu-id: 0
  - type: tee
    name: tee_msg
  - type: queue
    name: queue_msg
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvmsgconv
    name: nvmsgconv
    properties:
      config: /root/configs/generator/yolo26n_det_image/nvmsgconv.yml
      payload-type: 1
      msg2p-newapi: true
      frame-interval: 1
  - type: nvmsgbroker
    name: nvmsgbroker
    properties:
      proto-lib: /opt/nvidia/deepstream/deepstream/lib/libnvds_kafka_proto.so
      conn-str: ai_stream2_kafka;9092
      topic: ai_stream2_yolo26n_det_image
      config: /root/configs/generator/yolo26n_det_image/kafka.txt
      sync: false
      async: false
  - type: nvdetfadedrawer
    name: nvdetfadedrawer
    properties:
      interval: 50
      fade-time: 1
      show-label: true
  - type: nvosdbin
    name: nvosdbin
    properties:
      gpu-id: 0
      display-bbox: true
      display-text: true
      display-mask: false
  - type: nvvideoconvert
    name: nvvideoconvert
    properties:
      gpu-id: 0
  - type: nvdetlogger
    name: nvdetlogger
    properties:
      root: /root/logs/deepstream/yolo26n_det_image
      interval: 50
  - type: capsfilter
    name: capsfilter_jpeg
    properties:
      caps: video/x-raw(memory:NVMM), format=I420
  - type: nvjpegenc
    name: nvjpegenc
    properties:
      quality: 85
  - type: filesink
    name: filesink
    properties:
      location: /root/outputs/deepstream/yolo26n_det_image.jpg
      sync: false
      async: false
  edges:
    nvurisrcbin: nvstreammux
    nvstreammux: pgie
    pgie: nvdsanalytics
    nvdsanalytics: tee_msg
    tee_msg:
    - nvdetfadedrawer
    - queue_msg
    nvdetfadedrawer: nvosdbin
    queue_msg: nvmsgconv
    nvmsgconv: nvmsgbroker
    nvosdbin: nvvideoconvert
    nvvideoconvert: capsfilter_jpeg
    capsfilter_jpeg: nvdetlogger
    nvdetlogger: nvjpegenc
    nvjpegenc: filesink
