property:
  gpu-id: 0
  net-scale-factor: 0.00392156862745098
  onnx-file: /opt/models/yolov8n.onnx
  model-engine-file: /opt/models/yolov8n.onnx_b16_gpu0_fp16.engine
  labelfile-path: /opt/models/labels.txt
  batch-size: 16
  network-mode: 1
  num-detected-classes: 80
  process-mode: 1
  interval: 0
  cluster-mode: 2
  maintain-aspect-ratio: 1
  # infer-dims: 3;640;640  # uncomment if ONNX has dynamic input dims

class-attrs-all:
  topk: 20
  pre-cluster-threshold: 0.4
  nms-iou-threshold: 0.5
