property:
  gpu-id: 0
  gie-unique-id: 1
  net-scale-factor: 0.00392156862745098
  onnx-file: /app/models/yolov10n.onnx
  model-engine-file: /app/models/yolov10n.onnx_b1_gpu0_fp16.engine
  labelfile-path: /app/models/coco_labels.txt
  model-color-format: 0
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  batch-size: 1
  network-mode: 2
  num-detected-classes: 80
  process-mode: 1
  network-type: 100
  interval: 0
  cluster-mode: 4
  output-tensor-meta: 1

class-attrs-all:
  pre-cluster-threshold: 0.3
