property:
  gpu-id: 0
  net-scale-factor: 0.00392156862745098
  onnx-file: /opt/nvidia/deepstream/deepstream/samples/models/Primary_Detector/resnet18_trafficcamnet_pruned.onnx
  model-engine-file: /app/config/resnet18_trafficcamnet_pruned_b1_gpu0_fp16.engine
  labelfile-path: /opt/nvidia/deepstream/deepstream/samples/models/Primary_Detector/labels.txt
  batch-size: 1
  network-mode: 1
  num-detected-classes: 4
  process-mode: 1
  interval: 0
  cluster-mode: 2
  maintain-aspect-ratio: 1
  # infer-dims: 3;640;640  # uncomment if ONNX has dynamic input dims

class-attrs-all:
  topk: 20
  pre-cluster-threshold: 0.4
  nms-iou-threshold: 0.5
