pipeline_name: stgcnpp_yolo_pose_rtsp
streams:
  video1:
    url: rtsp://ai_stream2_mediamtx:8554/video1
    width: 1920
    height: 1080
    fps: 25
  video2:
    url: rtsp://ai_stream2_mediamtx:8554/video2
    width: 1920
    height: 1080
    fps: 25
type: StgcnppYoloPoseRTSPPipeline
generator: StgcnppYoloPoseRTSPGenerator
pgie:
  model_dir: /root/models/trt/yolo26n-pose
  class_attrs:
    all:
      conf: 0.25
  interval: 1
analyzer: null
tracker:
  class_id: 0
logger:
  interval: 1
  root: /root/logs/deepstream/stgcnpp_yolo_pose_rtsp
drawer: null
stgcnpp:
  model_dir: /root/models/trt/stgcnpp-ntu60-j
  interval: 1
