deepstream:
  nodes:
  - type: nvurisrcbin
    name: nvurisrcbin0
    properties:
      uri: rtsp://ai_stream2_mediamtx:8554/video1
      disable-audio: true
      select-rtp-protocol: 4
  - type: nvurisrcbin
    name: nvurisrcbin1
    properties:
      uri: rtsp://ai_stream2_mediamtx:8554/video2
      disable-audio: true
      select-rtp-protocol: 4
  - type: nvstreammux
    name: nvstreammux
    properties:
      batch-size: 2
      width: 1920
      height: 1080
      enable-padding: false
      batched-push-timeout: 40000
      gpu-id: 0
      live-source: true
  - type: nvsahipreprocess
    name: nvsahipreprocess
    properties:
      config-file: /root/configs/generator/yolo26n_seg_sahi_vis_rtsp/nvsahipreprocess.ini
      slice-width: 640
      slice-height: 640
      overlap-width-ratio: 0.2
      overlap-height-ratio: 0.2
      enable-full-frame: true
      gpu-id: 0
      unique-id: 15
      target-unique-ids: '1'
  - type: nvinfer
    name: pgie
    properties:
      config-file-path: /root/configs/generator/yolo26n_seg_sahi_vis_rtsp/pgie.yml
      batch-size: 18
      gpu-id: 0
      input-tensor-meta: true
      clip-object-outside-roi: false
  - type: queue
    name: queue_sahi
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvsahipostprocess
    name: nvsahipostprocess
    properties:
      gie-ids: '1'
      match-metric: 1
      match-threshold: 0.5
      class-agnostic: false
      enable-merge: true
      two-phase-nmm: true
  - type: nvdsanalytics
    name: nvdsanalytics
    properties:
      config-file: /root/configs/generator/yolo26n_seg_sahi_vis_rtsp/nvdsanalytics.yml
      gpu-id: 0
  - type: nvstreamdemux
    name: nvstreamdemux
  - type: queue
    name: queue_demux0
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvvideoconvert
    name: nvvideoconvert0
    properties:
      gpu-id: 0
  - type: nvosdbin
    name: nvosdbin0
    properties:
      gpu-id: 0
      display-bbox: true
      display-text: true
      display-mask: false
  - type: queue
    name: queue_enc0
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvv4l2h264enc
    name: nvv4l2h264enc0
    properties:
      bitrate: 4000000
      iframeinterval: 25
      preset-id: 1
      gpu-id: 0
  - type: h264parse
    name: h264parse0
  - type: rtspclientsink
    name: rtspclientsink0
    properties:
      location: rtsp://ai_stream2_mediamtx:8554/video1_ds
      sync: false
      async: false
  - type: queue
    name: queue_demux1
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvvideoconvert
    name: nvvideoconvert1
    properties:
      gpu-id: 0
  - type: nvosdbin
    name: nvosdbin1
    properties:
      gpu-id: 0
      display-bbox: true
      display-text: true
      display-mask: false
  - type: queue
    name: queue_enc1
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvv4l2h264enc
    name: nvv4l2h264enc1
    properties:
      bitrate: 4000000
      iframeinterval: 25
      preset-id: 1
      gpu-id: 0
  - type: h264parse
    name: h264parse1
  - type: rtspclientsink
    name: rtspclientsink1
    properties:
      location: rtsp://ai_stream2_mediamtx:8554/video2_ds
      sync: false
      async: false
  edges:
    nvurisrcbin0: nvstreammux
    nvurisrcbin1: nvstreammux
    nvstreammux: nvsahipreprocess
    nvsahipreprocess: pgie
    pgie: queue_sahi
    queue_sahi: nvsahipostprocess
    nvsahipostprocess: nvdsanalytics
    nvdsanalytics: nvstreamdemux
    queue_demux0: nvvideoconvert0
    nvvideoconvert0: nvosdbin0
    nvosdbin0: queue_enc0
    queue_enc0: nvv4l2h264enc0
    nvv4l2h264enc0: h264parse0
    h264parse0: rtspclientsink0
    queue_demux1: nvvideoconvert1
    nvvideoconvert1: nvosdbin1
    nvosdbin1: queue_enc1
    queue_enc1: nvv4l2h264enc1
    nvv4l2h264enc1: h264parse1
    h264parse1: rtspclientsink1
