# Generated by Django 5.2.16 on 2026-07-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stream',
            new_name='streams_str_group_i_e866ed_idx',
            old_name='streams_str_group_i_idx',
        ),
        migrations.AlterField(
            model_name='stream',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
