pipeline_name: yolo26n_pose_sahi_image
type: PoseSahiImagePipeline
generator: PoseSahiImageGenerator
input: /root/attachments/images/video1.png
output: /root/outputs/deepstream/yolo26n_pose_sahi_image.jpg
pgie:
  model_dir: /root/models/trt/yolo26n-pose
  class_attrs:
    all:
      conf: 0.25
  interval: 50
analyzer: null
logger:
  interval: 50
  root: /root/logs/deepstream/yolo26n_pose_sahi_image
drawer:
  interval: 50
  fade_time: 1
  show_label: true
  show_pose: true
  pose_threshold: 0.5
  mode: coco17
sahi:
  nvsahipreprocess:
    slice_width: 640
    slice_height: 640
    overlap_width_ratio: 0.2
    overlap_height_ratio: 0.2
  nvsahipostprocess_pose:
    oks_threshold: 0.2
