rtspclientsink0:
- nvurisrcbin0
- nvstreammux
- nvsahipreprocess
- pgie
- queue_sahi
- nvsahipostprocess_pose
- nvtracker
- nvdsanalytics
- nvstreamdemux
- queue_demux0
- nvvideoconvert0
- nvosdbin0
- queue_enc0
- nvv4l2h264enc0
- h264parse0
- rtspclientsink0
rtspclientsink1:
- nvurisrcbin1
- nvstreammux
- nvsahipreprocess
- pgie
- queue_sahi
- nvsahipostprocess_pose
- nvtracker
- nvdsanalytics
- nvstreamdemux
- queue_demux1
- nvvideoconvert1
- nvosdbin1
- queue_enc1
- nvv4l2h264enc1
- h264parse1
- rtspclientsink1
