pipeline_name: stgcnpp_rtmpose_video
type: StgcnppRtmposeVideoPipeline
generator: StgcnppRtmposeVideoGenerator
input: /root/attachments/videos/video1.mp4
pgie:
  model_dir: /root/models/trt/yolo26n
  class_attrs:
    0:
      conf: 0.25
  interval: 50
analyzer: null
tracker:
  class_id: 0
logger:
  interval: 1
  root: /root/logs/deepstream/stgcnpp_rtmpose_video
drawer: null
sgie:
  model_dir: /root/models/trt/rtmpose-t-body8
  interval: 1
stgcnpp:
  model_dir: /root/models/trt/stgcnpp-ntu60-j
  interval: 1
