# bash servers/export_trt/scripts/3_export.sh --input models/onnx/peoplenet --config servers/export_trt/templates/peoplenet.yaml
type: PEOPLENET
batch_size: 18
gpu_id: 0
precision: int8
opt_level: null
