generator: DetImageGenerator
input: /root/attachments/images/video1.png
output: /root/outputs/deepstream/peoplenet_image.jpg
pgie:
  model_dir: /root/models/trt/peoplenet
  class_attrs:
    all:
      conf: 0.25
analyzer: null
interval: 1
config_save_dir: /root/configs/generator/peoplenet_image
