[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short -q --strict-markers
markers =
    asyncio: async tests
asyncio_mode = auto
