deepstream:
  nodes:
  - type: nvurisrcbin
    name: src
    properties:
      uri: file:///root/attachments/videos/video1.mp4
      disable-audio: true
      select-rtp-protocol: 4
  - type: nvstreammux
    name: mux
    properties:
      batch-size: 1
      width: 1920
      height: 1080
      enable-padding: false
      batched-push-timeout: 40000
      gpu-id: 0
      live-source: false
  - type: nvsahipreprocess
    name: sahi_preprocess
    properties:
      config-file: /root/configs/generator/yolo26n_det_sahi_video/nvsahipreprocess.ini
      slice-width: 640
      slice-height: 640
      overlap-width-ratio: 0.2
      overlap-height-ratio: 0.2
      enable-full-frame: true
      gpu-id: 0
      unique-id: 15
      target-unique-ids: '1'
  - type: nvinfer
    name: pgie
    properties:
      config-file-path: /root/configs/generator/yolo26n_det_sahi_video/pgie.yml
      batch-size: 9
      gpu-id: 0
      input-tensor-meta: true
  - type: queue
    name: queue_sahi
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvsahipostprocess
    name: sahi_postprocess
    properties:
      gie-ids: '1'
      match-metric: 1
      match-threshold: 0.5
      class-agnostic: false
      enable-merge: true
      two-phase-nmm: true
  - type: nvosdbin
    name: osd
    properties:
      gpu-id: 0
      display-bbox: true
      display-text: true
  - type: nvvideoconvert
    name: nvvidconv
    properties:
      gpu-id: 0
  - type: nvv4l2h264enc
    name: encoder
    properties:
      bitrate: 4000000
      iframeinterval: 25
      preset-id: 1
      gpu-id: 0
  - type: h264parse
    name: h264parse
  - type: mp4mux
    name: mp4mux
  - type: filesink
    name: sink
    properties:
      location: /root/outputs/deepstream/yolo26n_det_sahi_video.mp4
      sync: false
      async: false
  edges:
    src: mux
    mux: sahi_preprocess
    sahi_preprocess: pgie
    pgie: queue_sahi
    queue_sahi: sahi_postprocess
    sahi_postprocess: osd
    osd: nvvidconv
    nvvidconv: encoder
    encoder: h264parse
    h264parse: mp4mux
    mp4mux: sink
