generator: SegVideoGenerator
input: /root/attachments/videos/video1.mp4
output: /root/outputs/yolo11n_seg_video.mp4
pgie:
  model_dir: /root/models/trt/yolo11n-seg
  class_attr:
    all:
      conf: 0.25
  class_on: null
analyzer: null
tracker: false
interval: 0
config_save_dir: /root/configs/generator/yolo11n_seg_video
