# Generated by Django 6.0.2 on 2026-04-06 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cameras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('object_count', '对象数量'), ('object_type', '对象类型'), ('zone_intrusion', '区域入侵'), ('line_crossing', '越线检测'), ('overcrowding', '拥挤检测')], max_length=30, verbose_name='规则类型')),
                ('conditions', models.JSONField(help_text='Schema 因 rule_type 而异', verbose_name='规则条件')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('cooldown_seconds', models.IntegerField(default=60, verbose_name='冷却时间(秒)')),
                ('notify_channels', models.JSONField(default=list, help_text='["websocket", "email", "webhook"]', verbose_name='通知渠道')),
                ('cameras', models.ManyToManyField(blank=True, help_text='空 = 全部摄像头', related_name='alert_rules', to='cameras.camera', verbose_name='关联摄像头')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='accounts.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '报警规则',
                'verbose_name_plural': '报警规则',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_at', models.DateTimeField(db_index=True, verbose_name='触发时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('acknowledged', '已确认'), ('resolved', '已解决')], default='pending', max_length=20, verbose_name='状态')),
                ('snapshot', models.JSONField(default=dict, verbose_name='触发时检测数据快照')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cameras.camera', verbose_name='触发摄像头')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.organization', verbose_name='所属组织')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='解决人')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.alertrule', verbose_name='触发规则')),
            ],
            options={
                'verbose_name': '报警记录',
                'verbose_name_plural': '报警记录',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
