generator: SegSahiVideoGenerator
input: /root/attachments/videos/video1.mp4
output: /root/outputs/deepstream/yolo11n_seg_sahi_video.mp4
pgie:
  model_dir: /root/models/trt/yolo11n-seg-sahi
  class_attrs:
    all:
      conf: 0.25
analyzer: null
tracker: null
interval: 50
sahi:
  nvsahipreprocess:
    slice_width: 640
    slice_height: 640
    overlap_width_ratio: 0.2
    overlap_height_ratio: 0.2
  nvsahipostprocess:
    match_threshold: 0.5
config_save_dir: /root/configs/generator/yolo11n_seg_sahi_video
