type: PresenceRTSPPipeline
name: firepipeline
config_dir: /root/configs/generator/firepipeline
logger:
  root: /root/logs/deepstream
  interval: 50
messager:
  topic: deepstream-detections
  host: ai_stream2_kafka
  port: 9092
debouncer:
  length: 10
  threshold: 0.5
  class_ids:
  - 0
  - 1
  mode: fold
capturer:
  output_dir: /root/configs/generator/firepipeline/capturer
