# Prerequisite: servers/generator/scripts/3_generate.sh --config topdown_pose_sahi_image

type: RtmposeSahiImagePipeline
name: topdown-pose-sahi-image
config_dir: /root/configs/generator/topdown_pose_sahi_image
drawer:
  show_label: true
  show_conf: true
logger:
  interval: 0
messager:
  topic: deepstream-detections
  host: ai_stream2_kafka
  port: 9092
