# Prerequisite: servers/generator/scripts/3_generate.sh --config topdown_pose_sahi_vis_video

type: RtmposeSahiVisVideoPipeline
name: topdown-pose-sahi-vis-video
config_dir: /root/configs/generator/topdown_pose_sahi_vis_video_no_interval
drawer:
  show_label: true
  show_conf: true
  interval: 1
  fade_time: 0
logger:
  interval: 1
messager:
  topic: deepstream-detections
  host: ai_stream2_kafka
  port: 9092
