# Prerequisite: servers/generator/scripts/3_generate.sh --config yolo26n_pose_image

type: PoseImagePipeline
name: yolo26n-pose-image
config_dir: /root/configs/generator/yolo26n_pose_image
drawer:
  show_label: true
  show_conf: true
logger:
  interval: 0
messager:
  topic: deepstream-detections
  host: ai_stream2_kafka
  port: 9092
