deepstream:
  nodes:
  - type: nvurisrcbin
    name: nvurisrcbin
    properties:
      uri: file:///root/attachments/videos/video1.mp4
      disable-audio: true
      select-rtp-protocol: 4
  - type: nvstreammux
    name: nvstreammux
    properties:
      batch-size: 1
      width: 1920
      height: 1080
      enable-padding: false
      batched-push-timeout: 40000
      gpu-id: 0
      live-source: false
  - type: nvinfer
    name: pgie
    properties:
      config-file-path: /root/configs/generator/yolo11n_det_vis_video_with_tracker/pgie.yml
      batch-size: 1
      gpu-id: 0
  - type: nvbboxsnapshot
    name: nvbboxsnapshot
  - type: nvtracker
    name: nvtracker
    properties:
      ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
      ll-config-file: /root/configs/generator/yolo11n_det_vis_video_with_tracker/nvtracker.yml
      tracker-width: 1920
      tracker-height: 1056
      gpu-id: 0
      operate-on-class-ids: ''
  - type: nvdsanalytics
    name: nvdsanalytics
    properties:
      config-file: /root/configs/generator/yolo11n_det_vis_video_with_tracker/nvdsanalytics.yml
      gpu-id: 0
  - type: tee
    name: tee_msg
  - type: queue
    name: queue_msg
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvmsgconv
    name: nvmsgconv
    properties:
      config: /root/configs/generator/yolo11n_det_vis_video_with_tracker/nvmsgconv.yml
      payload-type: 1
      msg2p-newapi: true
      frame-interval: 1
  - type: nvmsgbroker
    name: nvmsgbroker
    properties:
      proto-lib: /opt/nvidia/deepstream/deepstream/lib/libnvds_kafka_proto.so
      conn-str: ai_stream2_kafka;9092
      topic: ai_stream2_yolo11n_det_vis_video_with_tracker
      config: /root/configs/generator/yolo11n_det_vis_video_with_tracker/kafka.txt
      sync: false
      async: false
  - type: nvdetfadedrawerwithtracker
    name: nvdetfadedrawer
    properties:
      interval: 50
      fade-time: 1
      show-label: true
      show-snap: true
  - type: nvosdbin
    name: nvosdbin
    properties:
      gpu-id: 0
      display-bbox: true
      display-text: true
      display-mask: false
  - type: nvvideoconvert
    name: nvvideoconvert
    properties:
      gpu-id: 0
  - type: nvdetlogger
    name: nvdetlogger
    properties:
      root: /root/logs/deepstream/yolo11n_det_vis_video_with_tracker
      interval: 50
  - type: nvv4l2h264enc
    name: nvv4l2h264enc
    properties:
      bitrate: 4000000
      iframeinterval: 25
      preset-id: 1
      gpu-id: 0
  - type: h264parse
    name: h264parse
  - type: mp4mux
    name: mp4mux
  - type: filesink
    name: filesink
    properties:
      location: /root/outputs/deepstream/yolo11n_det_vis_video_with_tracker.mp4
      sync: false
      async: false
  edges:
    nvurisrcbin: nvstreammux
    nvstreammux: pgie
    pgie: nvbboxsnapshot
    nvbboxsnapshot: nvtracker
    nvtracker: nvdsanalytics
    nvdsanalytics: tee_msg
    tee_msg:
    - nvdetfadedrawer
    - queue_msg
    nvdetfadedrawer: nvosdbin
    queue_msg: nvmsgconv
    nvmsgconv: nvmsgbroker
    nvosdbin: nvvideoconvert
    nvvideoconvert: nvdetlogger
    nvdetlogger: nvv4l2h264enc
    nvv4l2h264enc: h264parse
    h264parse: mp4mux
    mp4mux: filesink
