property:
  gpu-id: 0
  onnx-file: ''
  model-engine-file: /root/models/trt/peoplenet/resnet34_peoplenet_int8.engine
  labelfile-path: /root/models/trt/peoplenet/labels.txt
  batch-size: 2
  network-mode: 1
  network-type: 0
  process-mode: 1
  model-color-format: 0
  num-detected-classes: 3
  gie-unique-id: 1
  interval: 49
  cluster-mode: 4
  maintain-aspect-ratio: 0
  net-scale-factor: 0.003921569790691137
  offsets: 0.0;0.0;0.0
  infer-dims: 3;544;960
  custom-lib-path: /opt/nvidia/deepstream/deepstream/lib/libnvds_infer_yolo.so
  parse-bbox-func-name: NvDsInferYoloE2E
  output-blob-names: output0
class-attrs-all:
  topk: 300
  pre-cluster-threshold: 0.25
