[property]
enable=1
target-unique-ids=1
# 0=NCHW, 1=NHWC
network-input-order=0
maintain-aspect-ratio=1
symmetric-padding=1
processing-width=640
processing-height=640
scaling-buf-pool-size=6
tensor-buf-pool-size=6
network-input-shape=9;3;640;640
network-color-format=0
tensor-data-type=0
tensor-name=images
scaling-pool-memory-type=0
scaling-pool-compute-hw=0
scaling-filter=0
custom-lib-path=/opt/nvidia/deepstream/deepstream/lib/gst-plugins/libcustom2d_preprocess.so
custom-tensor-preparation-function=CustomTensorPreparation
[user-configs]
pixel-normalization-factor=0.003921568