filesink:
- nvurisrcbin
- nvstreammux
- nvsahipreprocess
- pgie
- queue_sahi
- nvsahipostprocess_pose
- nvtracker
- nvdsanalytics
- nvosdbin
- nvvideoconvert
- nvv4l2h264enc
- h264parse
- mp4mux
- filesink
