generator: PoseVisVideoGenerator
input: /root/attachments/videos/video1.mp4
pgie:
  model_dir: /root/models/trt/yolo26n-pose
  class_attrs:
    all:
      conf: 0.25
  interval: 50
analyzer: null
tracker: null
output: /root/outputs/deepstream/yolo26n_pose_vis_video.mp4
config_save_dir: /root/configs/generator/yolo26n_pose_vis_video
