pipeline_name: yolo26n_det_sahi_vis_video
generator: DetSahiVisVideoGenerator
input: /root/attachments/videos/video1.mp4
pgie:
  model_dir: /root/models/trt/yolo26n
  class_attrs:
    all:
      conf: 0.25
  interval: 50
analyzer: null
tracker: null
logger:
  interval: 50
  root: /root/logs/deepstream/yolo26n_det_sahi_vis_video
drawer:
  interval: 50
  fade_time: 1
  show_label: true
sahi:
  nvsahipreprocess:
    slice_width: 640
    slice_height: 640
    overlap_width_ratio: 0.2
    overlap_height_ratio: 0.2
  nvsahipostprocess:
    match_threshold: 0.5
output: /root/outputs/deepstream/yolo26n_det_sahi_vis_video.mp4
