pipeline_name: topdown_pose_vis_video
type: TopdownPoseVisVideoPipeline
generator: TopdownPoseVisVideoGenerator
input: /root/attachments/videos/video1.mp4
pgie:
  model_dir: /root/models/trt/yolo26n
  class_attrs:
    0:
      conf: 0.25
  interval: 50
analyzer: null
tracker: null
logger:
  interval: 50
  root: /root/logs/deepstream/topdown_pose_vis_video
drawer:
  interval: 50
  fade_time: 1
  show_label: true
  show_pose: true
  pose_threshold: 0.5
  mode: coco17
output: /root/outputs/deepstream/topdown_pose_vis_video.mp4
sgie:
  model_dir: /root/models/trt/rtmpose-t-body8
  interval: 50
