deepstream:
  nodes:
  - type: nvurisrcbin
    name: nvurisrcbin
    properties:
      uri: file:///root/attachments/videos/video1.mp4
      disable-audio: true
      select-rtp-protocol: 4
  - type: nvstreammux
    name: nvstreammux
    properties:
      batch-size: 1
      width: 1920
      height: 1080
      enable-padding: false
      batched-push-timeout: 40000
      gpu-id: 0
      live-source: false
  - type: nvinfer
    name: nvinfer
    properties:
      config-file-path: /root/configs/generator/topdown_pose_video/pgie.yml
      batch-size: 1
      gpu-id: 0
  - type: nvtracker
    name: nvtracker
    properties:
      ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
      ll-config-file: /root/configs/generator/topdown_pose_video/nvtracker.yml
      tracker-width: 1920
      tracker-height: 1056
      gpu-id: 0
      operate-on-class-ids: '0'
  - type: nvinfer
    name: sgie
    properties:
      config-file-path: /root/configs/generator/topdown_pose_video/sgie.yml
      batch-size: 1
      gpu-id: 0
  - type: nvdsanalytics
    name: nvdsanalytics
    properties:
      config-file: /root/configs/generator/topdown_pose_video/nvdsanalytics.yml
      gpu-id: 0
  - type: nvosdbin
    name: nvosdbin
    properties:
      gpu-id: 0
      display-bbox: true
      display-text: true
      display-mask: false
  - type: nvvideoconvert
    name: nvvideoconvert
    properties:
      gpu-id: 0
  - type: nvv4l2h264enc
    name: nvv4l2h264enc
    properties:
      bitrate: 4000000
      iframeinterval: 25
      preset-id: 1
      gpu-id: 0
  - type: h264parse
    name: h264parse
  - type: mp4mux
    name: mp4mux
  - type: filesink
    name: filesink
    properties:
      location: /root/outputs/deepstream/topdown_pose_video.mp4
      sync: false
      async: false
  edges:
    nvurisrcbin: nvstreammux
    nvstreammux: nvinfer
    nvinfer: nvtracker
    nvtracker: sgie
    sgie: nvdsanalytics
    nvdsanalytics: nvosdbin
    nvosdbin: nvvideoconvert
    nvvideoconvert: nvv4l2h264enc
    nvv4l2h264enc: h264parse
    h264parse: mp4mux
    mp4mux: filesink
