generator: SegVisVideoGenerator
input: /root/attachments/videos/video1.mp4
pgie:
  model_dir: /root/models/trt/yolo11n-seg
  class_attrs:
    all:
      conf: 0.25
  interval: 50
analyzer: null
tracker: null
output: /root/outputs/deepstream/yolo11n_seg_vis_video.mp4
config_save_dir: /root/configs/generator/yolo11n_seg_vis_video
