deepstream:
  nodes:
  - type: nvurisrcbin
    name: nvurisrcbin0
    properties:
      uri: rtsp://ai_stream2_mediamtx:8554/video1
      disable-audio: true
      select-rtp-protocol: 4
  - type: nvurisrcbin
    name: nvurisrcbin1
    properties:
      uri: rtsp://ai_stream2_mediamtx:8554/video2
      disable-audio: true
      select-rtp-protocol: 4
  - type: nvstreammux
    name: nvstreammux
    properties:
      batch-size: 2
      width: 1920
      height: 1080
      enable-padding: false
      batched-push-timeout: 40000
      gpu-id: 0
      live-source: true
  - type: nvsahipreprocess
    name: nvsahipreprocess
    properties:
      config-file: /root/configs/generator/yolo10x_smoke_fire_sahi_rtsp/nvsahipreprocess.ini
      slice-width: 640
      slice-height: 640
      overlap-width-ratio: 0.2
      overlap-height-ratio: 0.2
      enable-full-frame: true
      gpu-id: 0
      unique-id: 15
      target-unique-ids: '1'
  - type: nvinfer
    name: pgie
    properties:
      config-file-path: /root/configs/generator/yolo10x_smoke_fire_sahi_rtsp/pgie.yml
      batch-size: 18
      gpu-id: 0
      input-tensor-meta: true
      clip-object-outside-roi: false
  - type: queue
    name: queue_sahi
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvsahipostprocess
    name: nvsahipostprocess
    properties:
      gie-ids: '1'
      match-metric: 1
      match-threshold: 0.5
      class-agnostic: false
      enable-merge: true
      two-phase-nmm: true
  - type: nvdsanalytics
    name: nvdsanalytics
    properties:
      config-file: /root/configs/generator/yolo10x_smoke_fire_sahi_rtsp/nvdsanalytics.yml
      gpu-id: 0
  - type: nvstreamdemux
    name: nvstreamdemux
  - type: queue
    name: queue_demux0
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvvideoconvert
    name: nvvideoconvert0
    properties:
      gpu-id: 0
  - type: tee
    name: tee_raw0
  - type: queue
    name: queue_raw0
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvvideoconvert
    name: nvvideoconvert_raw0
    properties:
      gpu-id: 0
  - type: capsfilter
    name: capsfilter_raw0
    properties:
      caps: video/x-raw(memory:NVMM), format=RGB
  - type: appsink
    name: appsink_raw0
    properties:
      emit-signals: true
      sync: false
      max-buffers: 1
      drop: true
      async: false
  - type: queue
    name: queue_osd0
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvvideoconvert
    name: nvvideoconvert_osd0
    properties:
      gpu-id: 0
  - type: capsfilter
    name: capsfilter_osd0
    properties:
      caps: video/x-raw(memory:NVMM), format=RGBA
  - type: nvosdbin
    name: nvosdbin0
    properties:
      gpu-id: 0
      display-bbox: true
      display-text: true
      display-mask: false
  - type: queue
    name: queue_vis0
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvvideoconvert
    name: nvvideoconvert_vis0
    properties:
      gpu-id: 0
  - type: capsfilter
    name: capsfilter_vis0
    properties:
      caps: video/x-raw(memory:NVMM), format=RGB
  - type: appsink
    name: appsink_vis0
    properties:
      emit-signals: true
      sync: false
      max-buffers: 1
      drop: true
      async: false
  - type: queue
    name: queue_demux1
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvvideoconvert
    name: nvvideoconvert1
    properties:
      gpu-id: 0
  - type: tee
    name: tee_raw1
  - type: queue
    name: queue_raw1
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvvideoconvert
    name: nvvideoconvert_raw1
    properties:
      gpu-id: 0
  - type: capsfilter
    name: capsfilter_raw1
    properties:
      caps: video/x-raw(memory:NVMM), format=RGB
  - type: appsink
    name: appsink_raw1
    properties:
      emit-signals: true
      sync: false
      max-buffers: 1
      drop: true
      async: false
  - type: queue
    name: queue_osd1
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvvideoconvert
    name: nvvideoconvert_osd1
    properties:
      gpu-id: 0
  - type: capsfilter
    name: capsfilter_osd1
    properties:
      caps: video/x-raw(memory:NVMM), format=RGBA
  - type: nvosdbin
    name: nvosdbin1
    properties:
      gpu-id: 0
      display-bbox: true
      display-text: true
      display-mask: false
  - type: queue
    name: queue_vis1
    properties:
      leaky: 2
      max-size-buffers: 4
  - type: nvvideoconvert
    name: nvvideoconvert_vis1
    properties:
      gpu-id: 0
  - type: capsfilter
    name: capsfilter_vis1
    properties:
      caps: video/x-raw(memory:NVMM), format=RGB
  - type: appsink
    name: appsink_vis1
    properties:
      emit-signals: true
      sync: false
      max-buffers: 1
      drop: true
      async: false
  edges:
    nvurisrcbin0: nvstreammux
    nvurisrcbin1: nvstreammux
    nvstreammux: nvsahipreprocess
    nvsahipreprocess: pgie
    pgie: queue_sahi
    queue_sahi: nvsahipostprocess
    nvsahipostprocess: nvdsanalytics
    nvdsanalytics: nvstreamdemux
    queue_demux0: nvvideoconvert0
    nvvideoconvert0: tee_raw0
    tee_raw0:
    - queue_raw0
    - queue_osd0
    queue_raw0: nvvideoconvert_raw0
    nvvideoconvert_raw0: capsfilter_raw0
    capsfilter_raw0: appsink_raw0
    queue_osd0: nvvideoconvert_osd0
    nvvideoconvert_osd0: capsfilter_osd0
    capsfilter_osd0: nvosdbin0
    nvosdbin0: queue_vis0
    queue_vis0: nvvideoconvert_vis0
    nvvideoconvert_vis0: capsfilter_vis0
    capsfilter_vis0: appsink_vis0
    queue_demux1: nvvideoconvert1
    nvvideoconvert1: tee_raw1
    tee_raw1:
    - queue_raw1
    - queue_osd1
    queue_raw1: nvvideoconvert_raw1
    nvvideoconvert_raw1: capsfilter_raw1
    capsfilter_raw1: appsink_raw1
    queue_osd1: nvvideoconvert_osd1
    nvvideoconvert_osd1: capsfilter_osd1
    capsfilter_osd1: nvosdbin1
    nvosdbin1: queue_vis1
    queue_vis1: nvvideoconvert_vis1
    nvvideoconvert_vis1: capsfilter_vis1
    capsfilter_vis1: appsink_vis1
