appsink_raw0:
- nvurisrcbin0
- nvstreammux
- nvsahipreprocess
- pgie
- queue_sahi
- nvsahipostprocess
- nvtracker
- nvdsanalytics
- nvstreamdemux
- queue_demux0
- nvvideoconvert0
- tee_raw0
- queue_raw0
- nvvideoconvert_raw0
- capsfilter_raw0
- appsink_raw0
appsink_vis0:
- nvurisrcbin0
- nvstreammux
- nvsahipreprocess
- pgie
- queue_sahi
- nvsahipostprocess
- nvtracker
- nvdsanalytics
- nvstreamdemux
- queue_demux0
- nvvideoconvert0
- tee_raw0
- queue_osd0
- nvvideoconvert_osd0
- capsfilter_osd0
- nvosdbin0
- queue_vis0
- nvvideoconvert_vis0
- capsfilter_vis0
- appsink_vis0
appsink_raw1:
- nvurisrcbin1
- nvstreammux
- nvsahipreprocess
- pgie
- queue_sahi
- nvsahipostprocess
- nvtracker
- nvdsanalytics
- nvstreamdemux
- queue_demux1
- nvvideoconvert1
- tee_raw1
- queue_raw1
- nvvideoconvert_raw1
- capsfilter_raw1
- appsink_raw1
appsink_vis1:
- nvurisrcbin1
- nvstreammux
- nvsahipreprocess
- pgie
- queue_sahi
- nvsahipostprocess
- nvtracker
- nvdsanalytics
- nvstreamdemux
- queue_demux1
- nvvideoconvert1
- tee_raw1
- queue_osd1
- nvvideoconvert_osd1
- capsfilter_osd1
- nvosdbin1
- queue_vis1
- nvvideoconvert_vis1
- capsfilter_vis1
- appsink_vis1
