streams:
  video1:
    url: rtsp://ai_stream2_mediamtx:8554/video1
    width: 1920
    height: 1080
    fps: 25
  video2:
    url: rtsp://ai_stream2_mediamtx:8554/video2
    width: 1920
    height: 1080
    fps: 25
generator: DetRTSPPresenceGenerator
pgie:
  model_dir: /root/models/trt/yolov10x-smoke-fire
  class_attrs:
    all:
      conf: 0.25
  interval: 50
analyzer: null
tracker: null
config_save_dir: /root/configs/generator/yolo10x_smoke_fire_rtsp
