pipeline_name: yolo10x_smoke_fire_rtsp
streams:
  video1:
    url: rtsp://ai_stream2_mediamtx:8554/video1
    width: 1920
    height: 1080
    fps: 25
  video2:
    url: rtsp://ai_stream2_mediamtx:8554/video2
    width: 1920
    height: 1080
    fps: 25
type: PresenceRTSPPipeline
generator: DetRTSPPresenceGenerator
pgie:
  model_dir: /root/models/trt/yolov10x-smoke-fire
  class_attrs:
    all:
      conf: 0.25
  interval: 50
analyzer: null
tracker: null
logger:
  interval: 50
  root: /root/logs/deepstream/yolo10x_smoke_fire_rtsp
drawer: null
event_coder:
  class_ids:
  - 0
  - 1
  event_names:
  - Fire
  - Smoke
  length: 5
  threshold: 0.5
  mode: fold
capturer:
  capture_codes: '1'
