# Generated by Django 6.0.2 on 2026-04-06 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaDeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=200, verbose_name='Kafka Topic')),
                ('partition_num', models.IntegerField(verbose_name='分区号')),
                ('offset', models.BigIntegerField(verbose_name='Offset')),
                ('raw_message', models.TextField(verbose_name='原始消息内容')),
                ('error_message', models.TextField(verbose_name='错误信息')),
            ],
            options={
                'verbose_name': 'Kafka 死信',
                'verbose_name_plural': 'Kafka 死信',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('detected_at', models.DateTimeField(db_index=True, verbose_name='检测时间')),
                ('ingested_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('frame_number', models.BigIntegerField(blank=True, null=True, verbose_name='帧号')),
                ('object_count', models.IntegerField(default=0, verbose_name='检测对象数')),
                ('detected_objects', models.JSONField(db_column='objects', default=list, help_text='[{type, confidence, bbox, object_id, classifier?, analytics?}]', verbose_name='检测对象')),
                ('analytics', models.JSONField(blank=True, help_text='越线计数、拥挤状态等 nvdsanalytics 帧级结果', null=True, verbose_name='帧级分析结果')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='cameras.camera', verbose_name='来源摄像头')),
            ],
            options={
                'verbose_name': '检测记录',
                'verbose_name_plural': '检测记录',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['camera', '-detected_at'], name='detections__camera__a7880c_idx'), models.Index(fields=['-detected_at'], name='detections__detecte_620aca_idx')],
            },
        ),
    ]
