sensor0:
  enable: 1
  type: Camera
  id: stream_0
  description: rtsp://ai_stream2_mediamtx:8554/video1
sensor1:
  enable: 1
  type: Camera
  id: stream_1
  description: rtsp://ai_stream2_mediamtx:8554/video2
