pipeline_name: yolo26n_det_video
type: DetVideoPipeline
generator: DetVideoGenerator
input: /root/attachments/videos/video1.mp4
pgie:
  model_dir: /root/models/trt/yolo26n
  class_attrs:
    all:
      conf: 0.25
  interval: 50
analyzer: null
tracker: null
logger:
  interval: 50
  root: /root/logs/deepstream/yolo26n_det_video
drawer: null
