property:
  enable: 1
  config-width: 1920
  config-height: 1080
  osd-mode: 2
  display-font-size: 12
roi-filtering-stream-0:
  enable: 1
  class-id: -1
  inverse-roi: 0
  roi-FLOOR: 160;60;1760;60;1760;1020;160;1020
overcrowding-stream-0:
  enable: 1
  class-id: 0
  object-threshold: 5
  time-threshold: 2000
  roi-CLUSTER: 320;360;980;360;980;760;320;760
line-crossing-stream-0:
  enable: 1
  extended: 0
  class-id: 0
  mode: balanced
  line-crossing-CrossDown: 960;400;960;680;200;540;1720;540
  line-crossing-CrossUp: 960;680;960;400;200;540;1720;540
direction-detection-stream-0:
  enable: 1
  class-id: 0
  mode: loose
  direction-South: 960;400;960;720
  direction-North: 960;720;960;400
