generator: DetVideoGenerator
input: /root/attachments/videos/video1.mp4
output: /root/outputs/deepstream/yolo26n_det_video_with_tracker.mp4
pgie:
  model_dir: /root/models/trt/yolo26n
  class_attrs:
    all:
      conf: 0.25
analyzer: null
tracker:
  class_id: -1
interval: 50
config_save_dir: /root/configs/generator/yolo26n_det_video_with_tracker
