property:
  gpu-id: 0
  onnx-file: ''
  model-engine-file: /root/models/trt/yolo26n/yolo26n.engine
  labelfile-path: /root/models/trt/yolo26n/labels.txt
  batch-size: 2
  network-mode: 2
  network-type: 0
  process-mode: 1
  model-color-format: 0
  num-detected-classes: 80
  gie-unique-id: 1
  interval: 49
  cluster-mode: 4
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  force-implicit-batch-dim: 0
  net-scale-factor: 0.003921569790691137
  infer-dims: 3;640;640
  custom-lib-path: /opt/nvidia/deepstream/deepstream/lib/libnvds_infer_yolo.so
  parse-bbox-func-name: NvDsInferYoloE2E
  output-blob-names: output0
  filter-out-class-ids: 1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20;21;22;23;24;25;26;27;28;29;30;31;32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;53;54;55;56;57;58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79
class-attrs-all:
  topk: 300
  pre-cluster-threshold: 0.25
class-attrs-0:
  pre-cluster-threshold: 0.25
