generator: YoloDetSahiConfigGenerator
streams:
- rtsp://ai_stream2_mediamtx:8554/video1
- rtsp://ai_stream2_mediamtx:8554/video2
pgie_model_dir: /root/models/trt/yolo26n_sahi
config_save_dir: /root/configs/generator/yolo26n_det_sahi_rtsp
enable_visualized_rtsp: true
enable_kafka: false
enable_nvtracker: false
interval: 0
pgie_class_attr:
  all:
    conf: 0.25
pgie_class_on: null
nvdsanalytics_config: null
sahi_config:
  nvsahipreprocess:
    slice_width: 640
    slice_height: 640
    overlap_width_ratio: 0.2
    overlap_height_ratio: 0.2
  nvsahipostprocess:
    match_threshold: 0.5
