property:
  gpu-id: 0
  onnx-file: ''
  model-engine-file: /root/models/trt/yolo11n-seg/yolo11n-seg.engine
  labelfile-path: /root/models/trt/yolo11n-seg/labels.txt
  batch-size: 2
  network-mode: 2
  network-type: 3
  process-mode: 1
  model-color-format: 0
  num-detected-classes: 80
  gie-unique-id: 1
  interval: 50
  cluster-mode: 4
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  scaling-filter: 1
  scaling-compute-hw: 0
  net-scale-factor: 0.00392156862745098
  infer-dims: 3;640;640
  custom-lib-path: /app/libs/libnvdsinfer_custom_impl_Yolo_seg.so
  parse-bbox-instance-mask-func-name: NvDsInferParseYoloSeg
  output-instance-mask: 1
  segmentation-threshold: 0.5
class-attrs-all:
  topk: 300
  pre-cluster-threshold: 0.25
