# Generated by Django 6.0.2 on 2026-04-06 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(help_text='对应 DeepStream camera_id / Kafka sensorId', max_length=100, unique=True, verbose_name='DeepStream Camera ID')),
                ('name', models.CharField(max_length=200, verbose_name='摄像头名称')),
                ('rtsp_url', models.CharField(max_length=500, verbose_name='RTSP 地址')),
                ('status', models.CharField(choices=[('offline', '离线'), ('connecting', '连接中'), ('online', '在线'), ('error', '异常')], default='offline', max_length=20, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='accounts.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '摄像头',
                'verbose_name_plural': '摄像头',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticsZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='区域名称')),
                ('zone_type', models.CharField(choices=[('roi', 'ROI 区域'), ('line_crossing', '越线检测'), ('overcrowding', '拥挤检测'), ('direction', '方向检测')], max_length=20, verbose_name='区域类型')),
                ('coordinates', models.JSONField(help_text='[[x1,y1], [x2,y2], ...] 基于 1920x1080 分辨率', verbose_name='坐标点列表')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='类型特定配置')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_zones', to='cameras.camera', verbose_name='关联摄像头')),
            ],
            options={
                'verbose_name': '分析区域',
                'verbose_name_plural': '分析区域',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_groups', to='accounts.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '摄像头分组',
                'verbose_name_plural': '摄像头分组',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='cameras.cameragroup', verbose_name='所属分组'),
        ),
    ]
