pipeline_name: stgcnpp_yolo_pose_vis_video
type: StgcnppYoloPoseVisVideoPipeline
generator: StgcnppYoloPoseVisVideoGenerator
input: /root/attachments/videos/video1.mp4
pgie:
  model_dir: /root/models/trt/yolo26n-pose
  class_attrs:
    all:
      conf: 0.25
  interval: 1
analyzer: null
tracker:
  class_id: 0
logger:
  interval: 1
  root: /root/logs/deepstream/stgcnpp_yolo_pose_vis_video
drawer:
  interval: 50
  fade_time: 1
  show_label: true
  show_pose: true
  pose_threshold: 0.5
  mode: coco17
output: /root/outputs/deepstream/stgcnpp_yolo_pose_vis_video.mp4
stgcnpp:
  model_dir: /root/models/trt/stgcnpp-ntu60-j
  interval: 1
