# Generated by Django 6.0.2 on 2026-04-06 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('detector', '检测器'), ('tracker', '跟踪器')], max_length=20, verbose_name='模型类型')),
                ('framework', models.CharField(choices=[('onnx', 'ONNX'), ('engine', 'TensorRT Engine'), ('custom', '自定义')], default='onnx', max_length=20, verbose_name='模型框架')),
                ('model_file', models.CharField(max_length=500, verbose_name='模型文件路径')),
                ('label_file', models.CharField(blank=True, default='', max_length=500, verbose_name='标签文件路径')),
                ('config', models.JSONField(default=dict, help_text='因 model_type 而异的配置参数', verbose_name='模型配置')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='版本号')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='accounts.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': 'AI 模型',
                'verbose_name_plural': 'AI 模型',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PipelineProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='管道名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('analytics_enabled', models.BooleanField(default=True, verbose_name='启用 nvdsanalytics')),
                ('analytics_config_stale', models.BooleanField(default=False, help_text='摄像头增删后自动标记，提示用户重新部署', verbose_name='分析配置需要重新部署')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('detector', models.ForeignKey(limit_choices_to={'model_type': 'detector'}, on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_as_detector', to='pipelines.aimodel', verbose_name='主检测模型')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_profiles', to='accounts.organization', verbose_name='所属组织')),
                ('tracker', models.ForeignKey(blank=True, limit_choices_to={'model_type': 'tracker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_as_tracker', to='pipelines.aimodel', verbose_name='跟踪配置')),
            ],
            options={
                'verbose_name': '管道配置',
                'verbose_name_plural': '管道配置',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraModelBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_binding', to='cameras.camera', verbose_name='关联摄像头')),
                ('pipeline_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_bindings', to='pipelines.pipelineprofile', verbose_name='管道配置')),
            ],
            options={
                'verbose_name': '摄像头模型绑定',
                'verbose_name_plural': '摄像头模型绑定',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
